Repository GetThatFlightOut/GTFO-FE, pull requests merged in 2021-01, with the labels that each got.

#32 Flight show page
  README.md
  app/controllers/application_controller.rb
  app/controllers/flights_controller.rb
  app/facades/search_facade.rb
  app/poros/trip.rb
  app/services/backend_service.rb
  app/views/flights/index.html.erb
  app/views/flights/show.html.erb
  config/environments/development.rb
  config/routes.rb
  spec/features/flights/flight_information_service_spec.rb
  spec/features/flights/show_spec.rb
  spec/fixtures/flight_data_return.json
  spec/poros/trip_spec.rb
  spec/service/flight_service_spec.rb
Labels: front end

#41 Fix the integration problems
  app/controllers/flights_controller.rb
  app/facades/search_facade.rb
  app/poros/trip.rb
  app/views/welcome/index.html.erb
  spec/features/flights/flight_information_service_spec.rb
  spec/features/flights/show_spec.rb
  spec/fixtures/flight_data_return.json
  spec/fixtures/flight_data_single_return.json
  spec/poros/trip_spec.rb
  spec/service/flight_service_spec.rb
Labels: front end

#67 Show page style
  app/assets/images/air.png
  app/assets/images/hotels.jpeg
  app/assets/images/plane.jpeg
  app/assets/stylesheets/application.scss
  app/views/flights/show.html.erb
Labels: front end, sprint 3, styling

#69 Update json data
  spec/features/flights/flight_information_service_spec.rb
  spec/features/flights/show_spec.rb
  spec/fixtures/flight_data_return.json
  spec/poros/trip_spec.rb
Labels: front end, sprint 3

#68 Flights index styling
  app/assets/images/lotion.jpg
  app/assets/images/sandals.jpg
  app/assets/images/snowman.jpg
  app/assets/images/sweater.jpg
  app/assets/stylesheets/application.scss
  app/views/flights/_flight_partial.html.erb
  app/views/flights/index.html.erb
  app/views/layouts/application.html.erb
  spec/features/flights/flight_information_service_spec.rb
  spec/features/flights/show_spec.rb
  spec/features/welcome/landing_spec.rb
Labels: front end, sprint 3, styling

#79 Moving plane
  app/assets/images/plane_bkgrnd.png
  app/assets/images/welcome_plane.png
  app/assets/stylesheets/application.scss
  app/views/welcome/index.html.erb
Labels: front end, sprint 3, styling

#80 Welcome stylin
  app/views/welcome/index.html.erb
Labels: front end, sprint 3, styling

#81 Implemented week weather display functionality
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/views/flights/show.html.erb
  spec/features/flights/show_spec.rb
Labels: front end, sprint 3, styling

#84 Be communication update
  app/facades/weather_facade.rb
  spec/facades/weather_facade_spec.rb
  spec/features/flights/flight_information_service_spec.rb
  spec/features/flights/show_spec.rb
  spec/fixtures/flight_data_return.json
  spec/fixtures/flights.json
  spec/poros/trip_spec.rb
Labels: extension, front end

#85 Better plane
  app/views/welcome/index.html.erb
Labels: front end, sprint 3, styling

#92 deleted weather facade and moved in facade logic to trip poro
  app/controllers/flights_controller.rb
  app/facades/search_facade.rb
  app/facades/weather_facade.rb
  app/poros/trip.rb
  spec/facades/weather_facade_spec.rb
  spec/poros/trip_spec.rb
Labels: sprint 3
